# Generated by Django 4.1.3 on 2022-11-23 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Login')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('repeat_password', models.CharField(max_length=255, verbose_name='password')),
            ],
        ),
    ]
