# Generated by Django 4.1.3 on 2022-11-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createresume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Create_resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('surname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('gender', models.CharField(max_length=255, verbose_name='Пол')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('tell', models.CharField(max_length=255, verbose_name='Номер Телефона')),
                ('age', models.CharField(max_length=255, verbose_name='Возраст')),
                ('location', models.CharField(max_length=255, verbose_name='Местоположение')),
                ('descr', models.CharField(max_length=255, verbose_name='Описание о себе')),
                ('descr_hardSkill', models.CharField(max_length=255, verbose_name='Описание HardSkill')),
                ('photo', models.ImageField(upload_to='images')),
            ],
        ),
    ]
