# Generated by Django 4.1.3 on 2022-11-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createresume', '0002_create_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='repeat_password',
        ),
        migrations.AlterField(
            model_name='create_resume',
            name='descr',
            field=models.TextField(max_length=255, verbose_name='Описание о себе'),
        ),
        migrations.AlterField(
            model_name='create_resume',
            name='descr_hardSkill',
            field=models.TextField(max_length=255, verbose_name='Описание HardSkill'),
        ),
    ]
